name: deploy-project

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVERIP }}
          username: ${{ secrets.SERVERUSER }}
          key: ${{ secrets.LARAVEL_ADVANCED_SSH_KEY }}

          script: |
            cd /root/laravel_advanced

            echo "Pull latest code..."
            git pull origin main
            
            docker compose up -d

            echo "Run migrations..."
            docker compose exec -T laravel-app php artisan migrate --force

            echo "Clear Laravel cache..."
            docker compose exec -T laravel-app php artisan optimize:clear

            echo "Deployment completed!"
            